[project]
name = "tabembedbench"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "liac-arff==2.5.0",
    "marimo>=0.14.16",
    "mlflow>=3.2.0",
    "plotly-express>=0.4.1",
    "polars>=1.32.2",
    "ruff>=0.12.8",
    "scikit-learn>=1.6.1",
    "tabicl>=0.1.3",
    "tabpfn>=2.1.2",
    "torch>=2.1.0",
    "torchvision>=0.16.0",
    "torchaudio>=2.1.0",
    "huggingface-hub>=0.34.4",
    "seaborn>=0.13.2",
    "kaleido>=1.0.0",
    "umap-learn>=0.5.9.post2",
    "streamlit>=1.48.1",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.uv.sources]
torch = { index = "pytorch-cu121", marker = "platform_system != 'Darwin'" }
torchvision = { index = "pytorch-cu121", marker = "platform_system != 'Darwin'" }
torchaudio = { index = "pytorch-cu121", marker = "platform_system != 'Darwin'" }

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = ["E", "W", "F", "I"]  # E/W (pycodestyle), F (pyflakes), I (isort)

[tool.ruff.lint.isort]
known-third-party = []

