[project]
name = "tabiclexpierments"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fsspec>=2025.7.0",
    "marimo>=0.14.16",
    "mlflow>=3.2.0",
    "plotly-express>=0.4.1",
    "polars>=1.32.2",
    "ruff>=0.12.8",
    "scikit-learn>=1.6.1",
    "tabicl>=0.1.3",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
