[project]
name = "tabiclexpierments"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "liac-arff==2.5.0",
    "marimo>=0.14.16",
    "mlflow>=3.2.0",
    "plotly-express>=0.4.1",
    "polars>=1.32.2",
    "ruff>=0.12.8",
    "scikit-learn>=1.6.1",
    "tabicl>=0.1.3",
    "tabpfn>=2.1.2",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "torchaudio>=2.0.0",

]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"

